### ISSUE TITLE
Can you make it node 6 compatible?

### ISSUE THREAD

**Issue by vekexasia** [josser/node-glacier-uploader#1]
I see you use ** only once. 

Is there a particoular reason why Math.pow was not used ?

**Comment by josser** [comment]
@vekexasia Just because of airibnb eslint preset
and yes, I don't like this too! )

**Comment by vekexasia** [comment]
Lol,

I like eslint presets but IMHO it should ease development and make code more standardized not less :)

It's not a big deal to me to use node 7 but It looks like a showstopper for some users. 

A tradeoff could be adding the `eslint ignore` line just for that exception? Or provide a babelified code.

**Comment by josser** [comment]
@vekexasia I think you are right.
6.x is LTS so it will be more correct to target it instead of 7.

**Comment by josser** [comment]
Fixed in 0.3.0
